### ISSUE TITLE
Issue with building the project as a java application: java.lang.String org.gradle.api.tasks.SourceSet.getCompileConfigurationName()

### ISSUE THREAD

**Issue by Medkallel** [kotlinguistics/IPA-Transcribers#2]
Hi I'm getting the following error when building the project as a java desktop app: 'java.lang.String org.gradle.api.tasks.SourceSet.getCompileConfigurationName()' in line 38

![image](https://user-images.githubusercontent.com/26349357/173557427-68ccbcf9-0be2-496a-a198-463ab2dd44f9.png)

Could you please indicate what the problem is and also what jdk version should I use

**Comment by Medkallel** [comment]
Hi again,
I was trying to run the ./gradlew shadowJar task
I used JDK 11 as well as 17, didn't work with either

**Comment by medavox** [comment]
I've just updated gradle and the project's dependencies, in case that helps (a lot has changed on Kotlin Multiplatofmr in the last 2 years).

Can you please try again and see if that's fixed it?

Also, which OS are you using?

**Comment by medavox** [comment]
actually it seems the shadowJar task is still broken. Please stand by
